version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - ".github/actions/**/*"
      - ".github/workflows"
    schedule:
      interval: "weekly"
    groups:
      create-combined-pull-request:
        patterns:
          - "*"
